version: '3'

services:
  front:
    env_file:
      - .env.local
    container_name: front
    restart: always
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - '80:3000'


